enum unikit_error_codes {
    UNIKIT_OK = 0,
    UNIKIT_ERROR_NONE = 0,
    UNIKIT_ERROR_TIMEOUT = -1,
    UNIKIT_ERROR_GENERIC = -2,
    UNIKIT_ERROR_NO_DATA = -3,
    UNIKIT_ERROR_NOT_PERMITTED = -4,
    UNIKIT_ERROR_INVALID_ARG = -5,
    UNIKIT_ERROR_IO = -6,
    UNIKIT_ERROR_BADAUTH = -7,
    UNIKIT_ERROR_CONNECT_FAILED = -8,
    UNIKIT_ERROR_INSUFFICIENT_RESOURCES = -9,
};